### ISSUE TITLE
Update Footer component with relevant links and copyright information

### ISSUE THREAD

**Issue by dead8309** [MLSAKIIT/devblogs-frontend#11]
Revamp the Footer component by adding relevant links (e.g., contact, privacy policy) and copyright information. Ensure it is visually consistent with the rest of the site using TailwindCSS.

No specific reference required for this task.

**Comment by madmaxWMFU** [comment]
Hi! Can you assign it to me?

**Comment by arkapaal** [comment]
can you assign this to me @dead8309

**Comment by dead8309** [comment]
Its already assigned to @madmaxWMFU

**Comment by madmaxWMFU** [comment]
The conflict was resolved.
