### ISSUE TITLE
Add Rich text editor to /create page using react-quill

### ISSUE THREAD

**Issue by dead8309** [MLSAKIIT/devblogs-frontend#17]
Add a rich text editor to the `/create` page using `react-quill` to enable users to format their blog content effectively.

**Reference**: [React-Quill Setup](https://www.npmjs.com/package/react-quill)

**Comment by arkapaal** [comment]
can i work upon this ?
@dead8309

**Comment by dead8309** [comment]
You can!! Although the issue says react-quill you can also use any other alternatives too like

- [Lexical](https://github.com/facebook/lexical)
- [TipTap](https://github.com/ueberdosis/tiptapl)
- [novel](https://novel.sh/)

**Comment by arkapaal** [comment]
issue resolved

**Comment by dead8309** [comment]
Added in #33
