### ISSUE TITLE
Enhance the various pages by adding CSS/TailwindCSS animations

### ISSUE THREAD

**Issue by dead8309** [MLSAKIIT/devblogs-frontend#19]
Add CSS/TailwindCSS animations for interactive elements like buttons, hover effects, and click events to enhance the UI across the site.

No specific reference required for this task.

**Comment by Akash-cloud001** [comment]
I can work on this assign this task to me with hacktoberfest label

**Comment by Akash-cloud001** [comment]
I have made the PR, please review it
