### ISSUE TITLE
Create Login form in /login route

### ISSUE THREAD

**Issue by dead8309** [MLSAKIIT/devblogs-frontend#2]
Implement a Login form on the `/login` route. The form should include fields for username and password and should be styled using TailwindCSS. This is the first step in building the authentication flow for the platform.

**Reference**: [Simple Authentication Guide](https://dev.to/sanjayttg/jwt-authentication-in-react-with-react-router-1d03)

**Comment by Amanaakash** [comment]
Hey @dead8309 , I want to work on this, can you please assign this to me?

**Comment by Amanaakash** [comment]
Hey @dead8309 , i have finished working on this feature .I have opened a pull request [https://github.com/MLSAKIIT/devblogs-frontend/pull/31](url) . Please let me know if i can add something more to it. Thanks .
