### ISSUE TITLE
Add a 404 page route

### ISSUE THREAD

**Issue by dead8309** [MLSAKIIT/devblogs-frontend#20]
Implement a 404 page that shows a user-friendly message and navigation options when a user lands on a non-existent route. Ensure it matches the site's theme and provides a link back to the homepage.

**Reference**: [404 Page Setup](https://www.geeksforgeeks.org/how-to-setup-404-page-in-react-routing/)

**Comment by aafaris** [comment]
Hi @dead8309, can you assign this to me? Thanks!

**Comment by dead8309** [comment]
Sure

**Comment by dead8309** [comment]
Sorry, @aafaris is already working on this issue. Could you please pick another one? If there's no progress by tomorrow, I'll assign it to you 🙂.

**Comment by dead8309** [comment]
Fixed in #28
