### ISSUE TITLE
Add a scroll-to-top button

### ISSUE THREAD

**Issue by dead8309** [MLSAKIIT/devblogs-frontend#22]
Implement a scroll-to-top button that appears when the user scrolls down the page. This button should smoothly scroll the user back to the top when clicked. Style it using TailwindCSS.

No specific reference required for this task.

**Comment by coder-pink** [comment]
@dead8309  Hi, can you assign this to me

**Comment by ayush-py-c** [comment]
Can you please assign me this

**Comment by eatulrajput** [comment]
Hi @dead8309, I would like to work on this issue, can you please assign me this?

**Comment by Tony-ArtZ** [comment]
@coder-pink are you still working on this ? Otherwise I am assigning this to someone else

**Comment by dead8309** [comment]
Added in #39
