### ISSUE TITLE
Add image optimization for the home page

### ISSUE THREAD

**Issue by dead8309** [MLSAKIIT/devblogs-frontend#24]
Optimize images on the home page to improve load times and performance. Utilize tools like Next.js's Image component (if using Next.js) or other React-based image optimizers. Ensure all images are compressed and served in modern formats like WebP.

No specific reference required for this task.

**Comment by NarayanRungta** [comment]
I want to work on this.

**Comment by Tony-ArtZ** [comment]
> I want to work on this.

Assigned ! Happy hacktoberfest!
