### ISSUE TITLE
Refactor Dark Mode State Management to Use Context API

### ISSUE THREAD

**Issue by Amanaakash** [MLSAKIIT/devblogs-frontend#30]
**Description**

Currently, the dark mode state is managed using **localStorage** and individual component state. This approach can lead to redundant code and makes it difficult to maintain a consistent theme across different components and pages.

**Proposed Solution:**

- Refactor the dark mode state management to use the React Context API.

- Create a **ThemeContext** to provide the dark mode state and a function to toggle the theme.

- Wrap the application in the **ThemeContext.Provider** to make the theme state accessible to all components.

- Update components to consume the **ThemeContext** instead of reading from **localStorage**.

**Benefits:**

- Centralized state management for the dark mode theme.

- Easier to maintain and update the theme state across the entire application.

- Improved code readability and reusability.

**Tasks:**

1. Create a **ThemeContext** in a new file (e.g., ThemeContext.jsx).

2. Implement a **ThemeProvider** component that manages the dark mode state and provides it to the rest of the application.

3. Wrap the App component with the **ThemeProvider**.

4. Update all components that currently manage the dark mode state to use the **ThemeContext** instead.

This refactor will enhance the maintainability and scalability of the theme management in the application.

**Comment by rycerzes** [comment]
It's yours!

PS: you can assign yourself to an issue, ask one of the maintainers for review :)

**Comment by Kr-Gagandeo1025** [comment]
Is this issue assigned to someone? If not, can you assign it to me? I got the API error handling issue assigned, but that is taking time because the API routes are not written, so I can do this in the meantime.

**Comment by Amanaakash** [comment]
I'm working on it. Will try to finish this by this evening.
