### ISSUE TITLE
Add validation to create Blogs page on /create route using react-hook-form and yup

### ISSUE THREAD

**Issue by dead8309** [MLSAKIIT/devblogs-frontend#4]
Integrate validation for the blog creation form on the `/create` route using `react-hook-form` and `yup`. Ensure that all fields are validated correctly, and error messages are displayed when necessary.

**Reference**: [Form Validation Video](https://www.youtube.com/watch?v=wlltgs5jmZw)

**Comment by Tony-ArtZ** [comment]
> Hey @dead8309 , I would like to work on this issue

Assigned! Happy hacktoberfest!
