### ISSUE TITLE
[Bug]: Dark mode is Not working properly for create New Blog form.

### ISSUE THREAD

**Issue by viki-777** [MLSAKIIT/devblogs-frontend#48]
**bug Description:**

In Dark Mode: The input text is not visible due to insufficient contrast between the text color and the background.

In Light Mode: The form background is too dark, making it visually inconsistent and difficult to read the content clearly.

**To Reproduce**
1. Go to 'home'
2. Click on 'create Blog'
3.Click on 'dark mode'

**Expected behavior**
In Dark Mode, input text should have a lighter color to ensure readability against the dark background.

In Light Mode, the form background should be light, ensuring proper contrast with the input fields and text for a clean, consistent look.

**Screenshots**
In light mode : form background is dark

![image](https://github.com/user-attachments/assets/0be88ba1-27f0-4b14-a619-8efacb0bc337)

In dark mode: input text is not visible

![image](https://github.com/user-attachments/assets/8e4b123c-3e46-4aa3-9411-f7529daa79c6)

**Comment by viki-777** [comment]
please assign me this issue

**Comment by rycerzes** [comment]
it's yours!

**Comment by Amanaakash** [comment]
Hey @rycerzes , I have a pr up which is related to this issue , previously the theme state management was localized and other components didn't have the access of the current theme to dynamically change it. I have refactored the state management using context api in pr #46. If you could verify that , then the blog post component can make use of the themeProvider to dynamically update for dark and light mode.
