### ISSUE TITLE
Add validation to create Register form on /register route using react-hook-form and yup

### ISSUE THREAD

**Issue by dead8309** [MLSAKIIT/devblogs-frontend#6]
Add validation logic for the registration form on the `/register` route using `react-hook-form` and `yup`. Ensure that fields like email are validated and error messages appear when needed.

**Reference**: [Form Validation Video](https://www.youtube.com/watch?v=wlltgs5jmZw)

**Comment by parth-1372** [comment]
Hello @dead8309 I want to Work On This , Can You Assign it to me.

**Comment by parth-1372** [comment]
Hello @dead8309 I have Create The PR #43 If You Want Any Further customization Suggest Me.
