### ISSUE TITLE
Integrate /get-blogs route on home page on Hero component with working carousel to automatically fetch data using useEffect with working readmore button

### ISSUE THREAD

**Issue by dead8309** [MLSAKIIT/devblogs-frontend#8]
Set up the Hero component on the homepage to integrate the `/get-blogs` route and fetch blog data automatically using `useEffect`. Include a working carousel and a 'read more' button for better navigation.

**Reference**: [React Fetch](https://jasonwatmore.com/react-fetch-add-bearer-token-authorization-header-to-http-request)

**Comment by prashantsingh181** [comment]
Hello, I would like to work on this issue.

**Comment by aadarsh10c** [comment]
Hey @dead8309 , i would like to work on this issue
