### ISSUE TITLE
Integrate /get-blogs route on home page on RecentPosts component to automatically fetch data using useEffect

### ISSUE THREAD

**Issue by dead8309** [MLSAKIIT/devblogs-frontend#9]
Modify the RecentPosts component on the homepage to automatically fetch data from the `/get-blogs` route using `useEffect`. Ensure the component displays the fetched blogs dynamically.

**Reference**: [React Fetch](https://jasonwatmore.com/react-fetch-add-bearer-token-authorization-header-to-http-request)

**Comment by parth-1372** [comment]
Hello @dead8309  I want to work on This issue.

**Comment by parth-1372** [comment]
Hello @dead8309 I have Create PR #45 Take A Look And Suggest me if Any other improvement Needed.
